services:
    citlaravel-nginx:
        build:
            context: .
            dockerfile: ./docker/nginx/Dockerfile
        image: citlaravel-nginx:0.2.0
        pull_policy: build
        security_opt:
            - no-new-privileges:true
        volumes:
            - citlaravel-storage-data:/var/www/storage:ro
        networks:
            - traefik-network
            - citlaravel-network
        env_file: .env
        restart: unless-stopped
        labels:
            - 'traefik.enable=true'

            - 'traefik.http.routers.${TRAEFIK_ROUTER}.entryPoints=websecure'
            - 'traefik.http.routers.${TRAEFIK_ROUTER}.rule=${TRAEFIK_HOST}'
            - 'traefik.http.routers.${TRAEFIK_ROUTER}.tls=true'
            - 'traefik.http.routers.${TRAEFIK_ROUTER}.tls.certresolver=leResolver'
            - 'traefik.http.routers.${TRAEFIK_ROUTER}.service=${TRAEFIK_SERVICE}@docker'
            - 'traefik.http.services.${TRAEFIK_SERVICE}.loadbalancer.server.port=80'

            - 'traefik.docker.network=traefik-network'
        init: true
        depends_on:
            citlaravel-php:
                condition: service_healthy
        healthcheck:
            test: ['CMD-SHELL', 'wget -qO- http://127.0.0.1:80 >/dev/null 2>&1 || exit 1']
            interval: 30s
            timeout: 5s
            retries: 3
            start_period: 5s

    citlaravel-php:
        build:
            context: .
            dockerfile: ./docker/php/Dockerfile
        image: citlaravel-php:0.2.0
        pull_policy: build
        security_opt:
            - no-new-privileges:true
        volumes:
            - citlaravel-storage-data:/var/www/storage
        networks:
            - citlaravel-postgres-network
            - citlaravel-redis-network
            - citlaravel-network
        env_file: .env
        restart: unless-stopped
        healthcheck:
            test: ['CMD-SHELL', 'php-fpm-healthcheck || exit 1']
            interval: 30s
            timeout: 5s
            retries: 3
            start_period: 5s

volumes:
    citlaravel-storage-data:
        name: citlaravel-storage-data

networks:
    traefik-network:
        name: traefik-network
        external: true
    citlaravel-postgres-network:
        name: citlaravel-postgres-network
        external: true
    citlaravel-redis-network:
        name: citlaravel-redis-network
        external: true
    citlaravel-network:
        name: citlaravel-network
