services:
    citpostgres:
        image: postgres:16
        container_name: citpostgres
        security_opt:
            - no-new-privileges:true
        volumes:
            - citpostgres-data:/var/lib/postgresql/data
            - ./backups/init.sql:/docker-entrypoint-initdb.d/init.sql
            - /etc/localtime:/etc/localtime:ro
            - /etc/timezone:/etc/timezone:ro
            - ./backups:/backups
        networks:
            - citpostgres-network
        env_file: .env
        restart: unless-stopped
        command: ['postgres']
        init: true
        healthcheck:
            test: ['CMD-SHELL', 'pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB']
            interval: 30s
            timeout: 5s
            retries: 3
            start_period: 5s

volumes:
    citpostgres-data:
        name: citpostgres-data

networks:
    citpostgres-network:
        name: citpostgres-network
