services:
    cit-redis:
        image: redis:8.6.2
        container_name: cit-redis
        security_opt:
            - no-new-privileges:true
        networks:
            - cit-redis-network
        env_file: .env
        restart: unless-stopped
        command: ['redis-server']
        init: true
        healthcheck:
            test: ['CMD', 'redis-cli', 'ping']
            interval: 30s
            timeout: 5s
            retries: 3
            start_period: 5s

networks:
    cit-redis-network:
        name: cit-redis-network
